### ISSUE TITLE
Google Chrome sync login timout

### ISSUE THREAD

**Issue by Juvencus** [sienori/Tab-Session-Manager#701]
## Short description
The Google account log in, necessary to sync to Google Drive, times out after a few hours. This happens only in Google Chrome (v88) and not Firefox (v85).

## Steps to reproduce
1. Start browser.
2. Sign in to Google Drive from Tab Session Manager settings.
3. Sync sessions.
4. Close Chrome and wait for few hours/next day.
5. Open Chrome and Tab Session Manager settings to confirm Google Drive is signed in.
6. Try to sync sessions. You are then asked to login again.

## Platform information
* Platform (OS): Windows 10
* Version of browser: Google Chrome 88.0.4324.146
* Version of Tab Session Manager: 6.4.0

**Comment by killerzula** [comment]
Can confirm that I am experiencing the same issue as well. Also it would be very helpful if it was possible to set up automatic syncing with Google Drive instead of having to do it manually everytime.

**Comment by nirim000** [comment]
I have the exact same problem.

**Platform information:**
Chrome Version: 88.0.4324.96 (Official Build) (64-bit)
OS: Manjaro Linux x86_64 
Host: X570 AORUS PRO WIFI -CF 
Kernel: 5.10.7-3-MANJARO 
Uptime: 3 hours, 18 mins 
Packages: 1736 (pacman), 5 (flatpak), 10 (snap) 
Shell: zsh 5.8 
Resolution: 1920x1080, 1360x768 
DE: GNOME 3.38.3 
WM: Mutter 
WM Theme: Matcha-dark-sea 
Theme: Matcha-dark-azul [GTK2/3] 
Icons: Papirus-Dark-Maia [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 5 3600X (12) @ 3.800GHz 
GPU: NVIDIA GeForce GTX 950 
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590 
Memory: 3046MiB / 32053MiB

**Comment by futureram** [comment]
I also have this problem, came here to see if it was reported already.

**Comment by sienori** [comment]
I'll investigate it.

**Comment by sienori** [comment]
I have fixed the problem of the login screen appearing every time. https://github.com/sienori/Tab-Session-Manager/commit/641e4db90a38aab62ddfac60a9959710135d92d6
It will be enabled in the next update.

**Comment by xHurricanex** [comment]
> I have fixed the problem of the login screen appearing every time. [641e4db](https://github.com/sienori/Tab-Session-Manager/commit/641e4db90a38aab62ddfac60a9959710135d92d6)
> It will be enabled in the next update.

Actually 3 problems were mentioned in this topic:
1) Sign off from Google after PC restart.
2) Sign off from Google after Chrome restart (without PC restart).
2) Sign off from Google after don't-know-what-happens in some time of regular work in Chrome.

The latest update fixed problems 1 and 2.
But problem 3 is still not solved.
I updated TSM today and after successful sign-in (maybe 30-40 minutes or so) I got a floating screen with the request to sign in to Google. I signed in - and that was OK for another 30-40 minutes.
